config/routes.rb
Portfolio::Application.routes.draw do

  resources :posts
  get '/posts/:post_id/pictures/new', to: 'posts#new_image', as: :new_image
  post '/posts/:post_id/pictures/new', to: 'posts#create_image', as: :create_image

  root :to => "static_pages#home"

  get "path", to: 'controller#action', as: :name_of_path
  get "home", to:  "static_pages#home", as: :home
  get "about", to:  "static_pages#about", as: :about
  get "contact", to:  "static_pages#contact", as: :contact
  get "posts", to: "posts#show", as: :posts
  get "contact_me", to: 'contact_me#new', as: :contact_me
  post "contact_me", to: 'contact_me#create', as: :contact_me

  devise_for :authors, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, :omniauth_providers => [:google_oauth2]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

	  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
	    data = access_token.info
	    author = Author.where(:email => data["email"]).first

	    unless author
	        author = Author.create(name: data["name"],
		    		   email: data["email"],
		    		   password: Devise.friendly_token[0,20]
		    		  )
	    end
	    author
	  end
  
end

app/models/contact_me.rb
class ContactMe < ActiveRecord::Base
  attr_accessible :body, :email, :subject
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :pictured, polymorphic: true
  attr_accessible :description, :title, :image
  has_attached_file :image, 
                      styles: { 
                      hd: "1200x1200>", 
                      large: "600x600>", 
                      medium: "300x300>", 
                      small: "150x150>", 
                      thumb: "100x100>", 
                      mini: "24x24>" }

validates :image, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :pictures, as: :pictured
  accepts_nested_attributes_for :pictures
  attr_accessible :Author, :body, :title, :image, :picture, :description, :pictures_attributes
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_me_controller.rb
class ContactMeController < ApplicationController
  def new
    @contact_me = ContactMe.new
  end

  def create
    @contact_me = ContactMe.new(params[:contact_me])
    if @contact_me.save
    ContactMeMailer.contact_me(@contact_me).deliver
    redirect_to root_path, notice: "Message Sent. Stay Classy"

    else
      flash.now.alert = "Please correct the errors below"
      render :new
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
	def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
     @author = Author.find_for_google_oauth2(request.env["omniauth.auth"], current_author)

    if @author.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @author, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_author_registration_url
    end
	end
	
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @post.pictures.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def new_image
    @post = Post.find(params[:post_id])
    @picture = @post.pictures.new(params[:picture])
  end

  def create_image
    @post = Post.find(params[:post_id])
    @picture = @post.pictures.new(params[:picture])
    if @picture.save
      redirect_to post_path(@post), notice: "Well Done. Picture has been uploaded"
    else
      flash.now.alert = 'Image could not be saved. See errors and try again.'
      render :new_picture
    end
  end
end

app/controllers/registration_controller.rb
registration_controller.rb

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  	@ip_info = IpInfo.new().get_ip_info
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_me_helper.rb
module ContactMeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contact_me/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Drop me a line</h1></br>
    <p>You can add, friend, or follow me... </p>
    <p>
      <%= mail_to "rholdy@gmail.com", 'Email', :class => "btn btn-primary btn-lg" %>
      <%= link_to "GitHub", "https://github.com/rholdy", :class => "btn btn-primary btn-lg", target: "blank" %> 
      <%= link_to "Twitter", "https://twitter.com/ryan_holdaway", :class => "btn btn-primary btn-lg", target: "blank" %> 
      <%= link_to "LinkedIn", "http://www.linkedin.com/pub/ryan-holdaway/79/9a3/116", :class => "btn btn-primary btn-lg", target: "blank" %> 
      <%= link_to "Google+", "https://plus.google.com/104574162680723731489/posts", :class => "btn btn-primary btn-lg", target: "blank" %> 
      <%= link_to "Facebook", "https://www.facebook.com/rholdy", :class => "btn btn-primary btn-lg", target: "blank" %> 
      <%= link_to "Quora", "http://www.quora.com/Ryan-Holdaway", :class => "btn btn-primary btn-lg", target: "blank" %>
    </p>
  </div>
</div>



<div class= "jumbotron" style= "float: right; width: 50%;" >
  <h2>...or you could use this cool form</h2></br>
  <%= simple_form_for @contact_me, url: contact_me_path do |f| %>
  <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :email, placeholder: "Your email goes here" %>
      <%= f.input :subject, placeholder: "Message subject goes here" %>
      <%= f.input :body, placeholder: "Your message goes here (make it good)", as: :text, input_html: {rows: 10} %>
      <%= f.button :submit, class: 'btn btn-primary', value: "Send" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container text-center'>
    <nav class="navbar" role="footer">
    <p>&copy; <%= Time.now.year %> Built by Ryan Holdaway using Ruby on Rails. All rights reserved </p>
    </nav>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissable alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation"> 
  <div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Portfolio", root_path, class: "navbar-brand btn" %></li>
      <li><%= link_to t(:about), about_path, class: "btn" %></li>
      <li><%= link_to t(:posts), posts_path, class: "btn" %></li>
      <li><%= link_to t(:contact), contact_me_path, class: "btn" %></li>
      <li> <%= mail_to "rholdy@gmail.com", ' ', :class => "icon-envelope btn" %> </li>
      <li> <%= link_to " ", "https://github.com/rholdy", :class => "icon-github btn", target: "blank" %> </li>
      <li> <%= link_to " ", "https://twitter.com/ryan_holdaway", :class => "icon-twitter btn", target: "blank" %> </li>
      <li> <%= link_to " ", "http://www.linkedin.com/pub/ryan-holdaway/79/9a3/116", :class => "icon-linkedin btn", target: "blank" %> </li>
      <li> <%= link_to " ", "https://plus.google.com/104574162680723731489/posts", :class => "icon-google-plus btn", target: "blank" %> </li>
      <li> <%= link_to " ", "https://www.facebook.com/rholdy", :class => "icon-facebook btn", target: "blank" %>  </li>
      <li> <%= link_to " ", "http://www.quora.com/Ryan-Holdaway", :class => "icon-flag btn", target: "blank" %> </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      
      <% if author_signed_in? %>
        <li> <p class='navbar-text'> Signed in as <%= current_author.email %></p> </li>
        <li><%= link_to "Sign Out", destroy_author_session_path, method: :delete, class: "btn" %></li>
      <% else %>
        <li><%= link_to "Sign in with Google", author_omniauth_authorize_path(:google_oauth2), class: "btn" %></li>
        <li><%= link_to "Sign Up", new_author_registration_path, class: "btn" %></li> 
        <li><%= link_to "Sign In", new_author_session_path, class: "btn" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html
  <html lang="en">

<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
</head>

<body>

  <%= render 'layouts/navigation' %>

  <div class="container">
  <%= render 'layouts/messages' %>
  <%= yield %>
  </div>
<%= render 'layouts/footer' %>
</body>

</html>

app/views/layouts/email.html.erb
<html>
  <head>
    <title><%= @message ? @message.subject : "Ryan Holdaway" %></title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">

  </head>

  <body>
  <%= yield %>
  </body>


</html>

app/views/pictures/_form.html.erb
<%= simple_form_for @picture, url: create_image_path(@post) do |f| %>
    <%= f.error_notification %>
    <%= f.input :image, required: true %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.button :submit %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Pictured</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.title %></td>
    <td><%= picture.description %></td>
    <td><%= picture.pictured %></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @picture.title %>
</p>

<p>
  <b>Description:</b>
  <%= @picture.description %>
</p>

<p>
  <b>Pictured:</b>
  <%= @picture.pictured %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :Author %>

      <%= f.simple_fields_for :pictures do |p| %>
      <h4> Include a Picture in your post </h4>
      <%= p.input :image %>
      <%= p.input :title %>
      <%= p.input :description%>
      <% end %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 class= "page-title">This is my blog</h1>

<div>
<%= link_to 'New Post', new_post_path, :class => "btn btn-primary btn-lg" %>

  <% @posts.each do |post| %>
    
    <div class= 'post' >
    <h3 class= 'post-title'><%= post.title %></br></h3>
    <p class= 'post-body'><%= post.body %></br><p>

    <%= image_tag post.pictures.first.image.url(:medium) unless post.pictures.empty? %></br></br>

    <%= post.Author %></br></br>
    
    </div>
    <%= link_to 'Edit', edit_post_path(post), :class => "btn btn-warning btn-lg" %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-lg" %>
    <%= link_to "New Image", new_image_path(post_id: post.id), :class => "btn btn-primary btn-lg" %>
    <% end %></br></br> 
    
<%= link_to 'New Post', new_post_path, :class => "btn btn-primary btn-lg" %>
    
</div> 

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/new_image.html.erb
<%= render 'pictures/form' %>

<%= link_to "Go Back", :back %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>Author:</b>
  <%= @post.Author %>
</p>







<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/about.html.erb
<% latitude, longitude = @ip_info['loc'].split(',') %>
<% if @ip_info %>
	<iframe id="forecast_embed" type="text/html" frameborder="0" height="245" width="100%" src="http://forecast.io/embed/#lat=<%= latitude %>&lon=<%= longitude %>&name=<%= @ip_info['city'] %>"> </iframe>
<% end %>

<!-- <html>
  <head>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

    google.load("feeds", "1");

    function initialize() {
      var feed = new google.feeds.Feed("http://www.rholdy.com/feed/");
      feed.load(function(result) {
        if (!result.error) {
          var container = document.getElementById("feed");
          for (var i = 0; i < result.feed.entries.length; i++) {
            var entry = result.feed.entries[i];
            var div = document.createElement("div");
            div.appendChild(document.createTextNode(entry.title));
            container.appendChild(div);
          }
        }
      });
    }
    google.setOnLoadCallback(initialize);

    </script>
  </head>
  <body>
    <div id="feed"></div>
  </body>
</html> -->

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome!</h1>
    <p>This is my Portfolio Page</p>
    <p><a href="http://youtu.be/dQw4w9WgXcQ" target="blank" class="btn btn-primary btn-lg">Get Busy</a></p></br>
  </div>
</div>